image:
  tag: 0.2
  repository: "gcr.io/heptio-images/ks-guestbook-demo"
  pullPolicy: "IfNotPresent"
ingress:
  path: "/"
  hosts:
  - "chart-example.local"
  annotations: {}
  tls: []
  enabled: false
replicaCount: 2
tolerations: []
service:
  port: 80
  type: "ClusterIP"
containerPort: 80
resources: {}
nodeSelector: {}
affinity: {}
